# Generated by Django 5.1.7 on 2025-04-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteID', models.IntegerField()),
                ('userID', models.IntegerField()),
                ('healthCardID', models.IntegerField()),
                ('sessionID', models.IntegerField()),
                ('voteColour', models.CharField(max_length=5)),
                ('ProgressNote', models.CharField(max_length=255)),
                ('Timestamp', models.DateTimeField(db_comment='Date and time when the user voted')),
            ],
        ),
    ]
