# Generated by Django 5.1.7 on 2025-04-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='ProgressNote',
            new_name='progressNote',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='Timestamp',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='id',
        ),
        migrations.AddField(
            model_name='team',
            name='teamID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='voteID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
