# Generated by Django 5.1.7 on 2025-04-17 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_name_team_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionID', models.IntegerField(primary_key=True, serialize=False)),
                ('sessionDate', models.DateTimeField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='healthCardID',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voteColour',
        ),
        migrations.AddField(
            model_name='vote',
            name='voteValue',
            field=models.CharField(choices=[('Green', 'Green'), ('Amber', 'Amber'), ('Red', 'Red')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='progressNote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='departmentID',
            field=models.ForeignKey(db_column='departmentID', on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='sessionID',
            field=models.ForeignKey(db_column='sessionID', on_delete=django.db.models.deletion.CASCADE, to='myapp.session'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('Engineer', 'Engineer'), ('TeamLeader', 'TeamLeader'), ('DepartmentLeader', 'DepartmentLeader'), ('SeniorManager', 'SeniorManager')], max_length=20)),
                ('departmentID', models.ForeignKey(blank=True, db_column='departmentID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department')),
                ('teamID', models.ForeignKey(blank=True, db_column='teamID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.team')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='userID',
            field=models.ForeignKey(db_column='userID', default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='userID',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
